### ISSUE TITLE
BUG on HA0.70.0

### ISSUE THREAD

**Issue by jyz0501** [TomerFi/home-assistant-custom-components#12]
2018-05-31 18:38:04 ERROR (Thread-4) [custom_components.sensor.broadlink_s1c] exception while getting sensors status: Traceback (most recent call last):
  File "/config/custom_components/sensor/broadlink_s1c.py", line 259, in run
    current_status = self._hub.get_sensors_status()
  File "/usr/lib/python3.6/site-packages/broadlink/__init__.py", line 782, in get_sensors_status
    response = self.send_packet(0x6a, packet)
  File "/usr/lib/python3.6/site-packages/broadlink/__init__.py", line 305, in send_packet
    response = self.cs.recvfrom(2048)
socket.timeout: timed out
Traceback (most recent call last):
  File "/config/custom_components/sensor/broadlink_s1c.py", line 259, in run
    current_status = self._hub.get_sensors_status()
  File "/usr/lib/python3.6/site-packages/broadlink/__init__.py", line 782, in get_sensors_status
    response = self.send_packet(0x6a, packet)
  File "/usr/lib/python3.6/site-packages/broadlink/__init__.py", line 305, in send_packet
    response = self.cs.recvfrom(2048)
socket.timeout: timed out

**Comment by TomerFi** [comment]
sorry for the delayed response,
is it still relevant?
