### ISSUE TITLE
HA not seeing S2 Alarm notifications

### ISSUE THREAD

**Issue by ChrisSutton123** [TomerFi/home-assistant-custom-components#13]
### Running HA 0.71,0 on Hassbian - Pi 3b+
Using Broadlink S2 alarm kit with two windowsand one movement sensor.

Initially everything works well, then after a couple of hours the status of the sensors do not update on HA
log file entries below:-

2018-06-12 17:20:11 DEBUG (MainThread) [custom_components.sensor.broadlink_s1c] starting platform setup
2018-06-12 17:20:12 INFO (MainThread) [custom_components.sensor.broadlink_s1c] succesfully connected to s1c hub
2018-06-12 17:20:12 DEBUG (MainThread) [custom_components.sensor.broadlink_s1c] Wall Motion Sensor initiated
2018-06-12 17:20:12 DEBUG (MainThread) [custom_components.sensor.broadlink_s1c] Key Fob initiated
2018-06-12 17:20:12 DEBUG (MainThread) [custom_components.sensor.broadlink_s1c] Door Sensor initiated
2018-06-12 17:20:12 DEBUG (MainThread) [custom_components.sensor.broadlink_s1c] window 1 initiated
2018-06-12 17:20:12 INFO (Thread-23) [custom_components.sensor.broadlink_s1c] starting sensors watch
2018-06-12 17:24:33 DEBUG (Thread-23) [custom_components.sensor.broadlink_s1c] status change tracked from: {"name": "Wall Motion Sensor", "type": "Motion Sensor", "serial": "2102e9a2", "order": 1, "status": 0}
2018-06-12 17:24:33 DEBUG (Thread-23) [custom_components.sensor.broadlink_s1c] status change tracked to: {"name": "Wall Motion Sensor", "type": "Motion Sensor", "serial": "2102e9a2", "order": 1, "status": 16}
2018-06-12 17:24:33 DEBUG (Thread-23) [custom_components.sensor.broadlink_s1c] launching event for Wall Motion Sensorfor state changed to motion_detected
.
.
2018-06-12 19:56:31 DEBUG (Thread-23) [custom_components.sensor.broadlink_s1c] launching event for Wall Motion Sensorfor state changed to no_motion
2018-06-12 19:56:31 DEBUG (MainThread) [custom_components.sensor.broadlink_s1c] Wall Motion Sensor received BROADLINK_S1C_SENSOR_UPDATE
2018-06-12 20:00:01 WARNING (Thread-23) [custom_components.sensor.broadlink_s1c] exception while getting sensors status: Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/sensor/broadlink_s1c.py", line 254, in run
    current_status = self._hub.get_sensors_status()
  File "/srv/homeassistant/lib/python3.5/site-packages/broadlink/__init__.py", line 782, in get_sensors_status
    response = self.send_packet(0x6a, packet)
  File "/srv/homeassistant/lib/python3.5/site-packages/broadlink/__init__.py", line 305, in send_packet
    response = self.cs.recvfrom(2048)
socket.timeout: timed out

2018-06-12 20:00:05 WARNING (Thread-23) [custom_components.sensor.broadlink_s1c] exception while getting sensors status: Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/sensor/broadlink_s1c.py", line 254, in run
    current_status = self._hub.get_sensors_status()
  File "/srv/homeassistant/lib/python3.5/site-packages/broadlink/__init__.py", line 782, in get_sensors_status
    response = self.send_packet(0x6a, packet)
  File "/srv/homeassistant/lib/python3.5/site-packages/broadlink/__init__.py", line 303, in send_packet
    self.cs.sendto(packet, self.host)
OSError: [Errno 101] Network is unreachable
.
.
2018-06-12 20:00:05 ERROR (Thread-23) [custom_components.sensor.broadlink_s1c] max exceptions allowed in watch loop exceeded, stoping watch loop
2018-06-12 20:00:05 INFO (Thread-23) [custom_components.sensor.broadlink_s1c] sensors watch done

Can you please help?
[home-assistant.log](https://github.com/TomerFi/home-assistant-custom-components/files/2096366/home-assistant.log)

**Comment by TomerFi** [comment]
it seems like a network connectivity issue...

**Comment by TomerFi** [comment]
is it still relevant?

**Comment by ChrisSutton123** [comment]
Sorry forgot about this. I am planning to buy a new alarm kit. I will test again
