### ISSUE TITLE
switcher_aio error in event call

### ISSUE THREAD

**Issue by BuSHari** [TomerFi/home-assistant-custom-components#15]
hello,

For the last days i'm getting an error when trying to events in the switcher, i can read the status but cant set.

```
2018-08-22 12:51:15 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall switcher_aio.turn_on (c:87d0f6db676f4543bb38a681cbc0e2d6): entity_id=['switcher_aio.control_device_switch']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1117, in _event_to_service_call
    await service_handler.func(service_call)
  File "/config/custom_components/switcher_aio/__init__.py", line 1007, in async_switcher_control
    _LOGGER.debug("received: " + service.service + " with call id: " + service.call_id)
AttributeError: 'ServiceCall' object has no attribute 'call_id'
```

there are some other people that getting that error also, see in that thread:
https://community.home-assistant.io/t/switcher-v2-all-in-one-full-control/50652 #

**Comment by ohadbenita** [comment]
Happens to me as well, would be useful to have it fixed

**Comment by mircer3** [comment]
anyone solve that issue?
I will be glad to know :)

**Comment by TomerFi** [comment]
sorry for the delayed response, the issue was actually fixed int the following [commit](https://github.com/TomerFi/home-assistant-custom-components/commit/949accf418aa8373c6c9a0f1f35f2c830730dc69)
