### ISSUE TITLE
HA 0.82.1 error

### ISSUE THREAD

**Issue by jyz0501** [TomerFi/home-assistant-custom-components#18]
exception while getting sensors status: Traceback (most recent call last):
  File "/config/custom_components/sensor/broadlink_s1c_0_82_1.py", line 259, in run
    current_status = self._hub.get_sensors_status()
  File "/config/deps/lib/python3.6/site-packages/broadlink/__init__.py", line 763, in get_sensors_status
    response = self.send_packet(0x6a, packet)
  File "/config/deps/lib/python3.6/site-packages/broadlink/__init__.py", line 286, in send_packet
    response = self.cs.recvfrom(2048)
socket.timeout: timed out

**Comment by TomerFi** [comment]
seems like a network connectivity issue...
have you tried looking at that direction?

**Comment by jyz0501** [comment]
> seems like a network connectivity issue...
> have you tried looking at that direction?

Is this a timeout error caused by a network connection problem?

**Comment by TomerFi** [comment]
I believe so.
