### ISSUE TITLE
0.86.2 update broke S1c component

### ISSUE THREAD

**Issue by Nasserish** [TomerFi/home-assistant-custom-components#29]
Hi

I wasn't able to update HA to 0.86.2 until I omitted S1C component, and now only one of my three door sensors appears. I am not able to add other sensors. 

exception while getting sensors status: Traceback (most recent call last):
  File "/config/custom_components/sensor/broadlink_s1c.py", line 259, in run
    current_status = self._hub.get_sensors_status()
  File "/usr/local/lib/python3.6/site-packages/broadlink/__init__.py", line 782, in get_sensors_status
    response = self.send_packet(0x6a, packet)
  File "/usr/local/lib/python3.6/site-packages/broadlink/__init__.py", line 305, in send_packet
    response = self.cs.recvfrom(2048)
socket.timeout: timed out

This is the most important component in my setup, and I really appreciate the work you've done.

Thanks

**Comment by Nasserish** [comment]
I've managed to fix it by changing sensors name in the Broadlink app.
Thanks
